### ISSUE TITLE
Concurrent access to 'R' is not allowed

### ISSUE THREAD

**Issue by tofferrosen** [CommitAnalyzingService/CAS_CodeRepoAnalyzer#16]

**Comment by puneetjindal** [comment]
@tofferrosen: Anybody can help me here. I am using R 3.2 and Python 2.7 on windows 10. I am trying to run robjects.r("load('mydata.Rdata')") where mydata is the file saved in workspace.

**Comment by tofferrosen** [comment]
Hi @puneetjindal - are you trying to run our project or is this your own code trying to use 'R' with python?
