### ISSUE TITLE
Incorrect detection of merge commits.

### ISSUE THREAD

**Issue by dpursehouse** [CommitAnalyzingService/CAS_CodeRepoAnalyzer#26]
From issue #2:
> You could also scan the commit message for "merge" as it is very reliably going to indicate a merge commit in association

This is not a good way to detect merge commits.  Particularly in the Gerrit project, the word "merge" is very often used in commit messages for commits that are not actually merges.

In git, a merge commit can be detected by the count of parent commits.  A merge commit will always have 2 parents, while a regular commit will only have 1.

**Comment by tofferrosen** [comment]
Great point, thank you. Will look into it this weekend.
